baseurl: https://yukis-blog.netlify.app/
DefaultContentLanguage: en
title: YuKi's Blog
theme: beautifulhugo
metaDataFormat: yaml
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  home: 'page/about/'
  comments: yes
  commit: no
  dateFormat: "October 10th"
  delayDisqus: yes
  favicon: img/snow.ico
  logo: /img/black_rose.png
  mainSections:
    - page
  readingTime: no
  rss: no
  showRelatedPosts: no
  socialShare: no
  subtitle: 真话不全说，假话全不说，只好说废话
  useHLJS: yes
  wordCount: no
Author:
  name: YuKi
  github: yuki-961004
  instagram: yuki_961004
  twitter: yuki_961004
menu:
  main:
    - name: About
      url: page/about/
      weight: 1 
    - name: Blog
      url: 'post/'
      weight: 2
 

